sudo: required
language: c
services:
  - docker
script:
  - make
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  fqdn: dockerfiles.bonachera.fr
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

